library(DBI)
library(ggplot2)
library(fitdistrplus)
library(ggpubr)
library(rpart)
library(tree)
library(randomForest)
library(rpart.plot)
library(fitdistrplus)
library(stringr)
library(dplyr)
library(triangle)
library(mc2d)
library(lattice)
library(PerformanceAnalytics)
library(sfsmisc)
library(HistogramTools)
library(fPortfolio)
library(party)
library(relaimpo)
library(caret)
library(earth)
library(Boruta)
#LIMPIAR VARIABLES
rm(list = ls(all.names = TRUE))

#Cargue de datos
BD <- read.csv("E:/PROYECTO/Documentos/PAYC/PROYECTO 10. REPLANIFICACIÓN PAYC/ANALISIS/OTRO SÍS, LA REC. DE CLI. Y LA SAT.  DE LOS CLI/SCRIPTS/BD SOLO VALORES PREGUNTAS.csv", header = TRUE, sep = ",")

#Parición de los datos
set.seed(3457)
indice <- createDataPartition(BD$SATISFACCION, p = .67,
                                  list = FALSE,
                                  times = 1)
BD_ENTRENO <-BD[indice,]
BD_CALIBRACION <-BD[-indice,]


#VARIABLE RETORNADO
#1. MÉTODO RANDOM FOREST -> SOLO ASPECTOS
set.seed(3457)
m_rf_r <-randomForest(BD$SATISFACCION ~ BD$COMPROMISOS001+BD$COMPROMISOS002+BD$COMPROMISOS003+BD$COMPROMISOS004+BD$COMPROMISOS005+BD$PERSONAL001+BD$PERSONAL002+BD$PERSONAL003+BD$PERSONAL004+BD$PERSONAL005+BD$PRODUCTOS001+BD$PRODUCTOS002+BD$PRODUCTOS003+BD$PRODUCTOS004+BD$PRODUCTOS005+BD$SOPORTE_ADMON001+BD$SOPORTE_ADMON002+BD$SOPORTE_ADMON003+BD$SOPORTE_ADMON004+BD$SOPORTE_ADMON005+BD$SOPORTE_DIR001+BD$SOPORTE_DIR002+BD$SOPORTE_DIR003+BD$SOPORTE_DIR004+BD$SOPORTE_DIR005+BD$SOPORTE_TEC001+BD$SOPORTE_TEC002+BD$SOPORTE_TEC003+BD$SOPORTE_TEC004+BD$SOPORTE_TEC005, importance=TRUE,ntree=1000)
error_rf_r<-mean(sqrt(m_rf_r[["mse"]]))
m_rf_r[["importance"]]
write.csv(m_rf_r[["importance"]], file = "E:/PROYECTO/Documentos/PAYC/PROYECTO 10. REPLANIFICACIÓN PAYC/ANALISIS/OTRO SÍS, LA REC. DE CLI. Y LA SAT.  DE LOS CLI/SCRIPTS/RANDOM_FOREST_PREGUNTA_SATISFACCION.csv")

#2. IMPORTANCIA RELATIVA -> REGRESIÓN LINEAL
m_rl_r_e<-lm(SATISFACCION ~ COMPROMISOS001+COMPROMISOS002+COMPROMISOS003+COMPROMISOS004+COMPROMISOS005+PERSONAL001+PERSONAL002+PERSONAL003+PERSONAL004+PERSONAL005+PRODUCTOS001+PRODUCTOS002+PRODUCTOS003+PRODUCTOS004+PRODUCTOS005+SOPORTE_ADMON001+SOPORTE_ADMON002+SOPORTE_ADMON003+SOPORTE_ADMON004+SOPORTE_ADMON005+SOPORTE_DIR001+SOPORTE_DIR002+SOPORTE_DIR003+SOPORTE_DIR004+SOPORTE_DIR005+SOPORTE_TEC001+SOPORTE_TEC002+SOPORTE_TEC003+SOPORTE_TEC004+SOPORTE_TEC005,data=BD_ENTRENO)
m_rl_r<-lm(BD$SATISFACCION ~ BD$COMPROMISOS001+BD$COMPROMISOS002+BD$COMPROMISOS003+BD$COMPROMISOS004+BD$COMPROMISOS005+BD$PERSONAL001+BD$PERSONAL002+BD$PERSONAL003+BD$PERSONAL004+BD$PERSONAL005+BD$PRODUCTOS001+BD$PRODUCTOS002+BD$PRODUCTOS003+BD$PRODUCTOS004+BD$PRODUCTOS005+BD$SOPORTE_ADMON001+BD$SOPORTE_ADMON002+BD$SOPORTE_ADMON003+BD$SOPORTE_ADMON004+BD$SOPORTE_ADMON005+BD$SOPORTE_DIR001+BD$SOPORTE_DIR002+BD$SOPORTE_DIR003+BD$SOPORTE_DIR004+BD$SOPORTE_DIR005+BD$SOPORTE_TEC001+BD$SOPORTE_TEC002+BD$SOPORTE_TEC003+BD$SOPORTE_TEC004+BD$SOPORTE_TEC005)
#imp_rl_r <-varImp(m_rl_r, scale = FALSE)
summary(m_rl_r)$coefficients[,4]  
BD_CALIBRACION$pred_rl_r <-predict(m_rl_r_e, select(BD_CALIBRACION,COMPROMISOS001,COMPROMISOS002,COMPROMISOS003,COMPROMISOS004,COMPROMISOS005,PERSONAL001,PERSONAL002,PERSONAL003,PERSONAL004,PERSONAL005,PRODUCTOS001,PRODUCTOS002,PRODUCTOS003,PRODUCTOS004,PRODUCTOS005,SOPORTE_ADMON001,SOPORTE_ADMON002,SOPORTE_ADMON003,SOPORTE_ADMON004,SOPORTE_ADMON005,SOPORTE_DIR001,SOPORTE_DIR002,SOPORTE_DIR003,SOPORTE_DIR004,SOPORTE_DIR005,SOPORTE_TEC001,SOPORTE_TEC002,SOPORTE_TEC003,SOPORTE_TEC004,SOPORTE_TEC005), type = "response")
#BD_CALIBRACION <- BD_CALIBRACION  %>% mutate(pred_rl_r1 = 1*(pred_rl_r > .53) + 0)
#BD_CALIBRACION <- BD_CALIBRACION  %>% mutate(accurate = 1*(pred_rl_r1 == RETORNADO))
error_rl_r <- 1 - mean((BD_CALIBRACION$pred_rl_r - BD_CALIBRACION$SATISFACCION)*(BD_CALIBRACION$pred_rl_r - BD_CALIBRACION$SATISFACCION))
mean((BD_CALIBRACION$pred_rl_r - BD_CALIBRACION$SATISFACCION)*(BD_CALIBRACION$pred_rl_r - BD_CALIBRACION$SATISFACCION))
write.csv(summary(m_rl_r)$coefficients[,4], file = "E:/PROYECTO/Documentos/PAYC/PROYECTO 10. REPLANIFICACIÓN PAYC/ANALISIS/OTRO SÍS, LA REC. DE CLI. Y LA SAT.  DE LOS CLI/SCRIPTS/LINEAL_PREGUNTA_SATISFACCION.csv")
mean(abs(BD_CALIBRACION$pred_rl_r - BD_CALIBRACION$SATISFACCION))

#3. IMPORTANCIA RELATIVA -> MARS -> NO APLICA
#4. REGRESIÓN LINEAL -> NO APLICA
#5. BORUTA
i=1
#warnings()
bortotr <- data.frame(a="",b="",c=0, stringsAsFactors=FALSE)
while(i<=100){
set.seed(as.numeric(Sys.time()))
m_bor_r <-Boruta(BD$SATISFACCION ~ BD$COMPROMISOS001+BD$COMPROMISOS002+BD$COMPROMISOS003+BD$COMPROMISOS004+BD$COMPROMISOS005+BD$PERSONAL001+BD$PERSONAL002+BD$PERSONAL003+BD$PERSONAL004+BD$PERSONAL005+BD$PRODUCTOS001+BD$PRODUCTOS002+BD$PRODUCTOS003+BD$PRODUCTOS004+BD$PRODUCTOS005+BD$SOPORTE_ADMON001+BD$SOPORTE_ADMON002+BD$SOPORTE_ADMON003+BD$SOPORTE_ADMON004+BD$SOPORTE_ADMON005+BD$SOPORTE_DIR001+BD$SOPORTE_DIR002+BD$SOPORTE_DIR003+BD$SOPORTE_DIR004+BD$SOPORTE_DIR005+BD$SOPORTE_TEC001+BD$SOPORTE_TEC002+BD$SOPORTE_TEC003+BD$SOPORTE_TEC004+BD$SOPORTE_TEC005, doTrace=0,maxRuns=500)
j= 1
#print(c("CORRIDA",i))
#print(m_bor_r$finalDecision)
  while(j<=length(m_bor_r$finalDecision)){
    temp <- data.frame(a=names(m_bor_r$finalDecision)[j],b=as.character(m_bor_r$finalDecision)[j],c=i)
    #print(c("VARIABLE",j))
    j=j+1
    bortotr<- union_all(bortotr,temp)
  }
i=i+1
}



#GUARDAR RESULTADOS EJECUCIÓN BORUTA
write.csv(bortotr, file = "E:/PROYECTO/Documentos/PAYC/PROYECTO 10. REPLANIFICACIÓN PAYC/ANALISIS/OTRO SÍS, LA REC. DE CLI. Y LA SAT.  DE LOS CLI/SCRIPTS/BORUTA_PREGUNTAS_SATISFACCION.csv")

#ARBOL DE REGRESIÓN
fit1 <- rpart(BD$SATISFACCION ~ BD$COMPROMISOS +BD$PERSONAL+BD$PRODUCTOS+BD$SOPORTE_ADMON+BD$SOPORTE_DIR+BD$SOPORTE_TEC, 
              method="anova",control=rpart.control(minsplit=10, cp=0.001))

#plotcp(fit1) # visualize cross-validation results 
summary(fit1) # detailed summary of splits

#GRAFICAR
plot(fit1, uniform=TRUE,  compress = TRUE
)
text(fit1,  use.n=TRUE,all=TRUE, cex=.7,fancy=FALSE,pretty=NULL)

post(fit1, file = "E:/PROYECTO/Documentos/PAYC/PROYECTO 10. REPLANIFICACIÓN PAYC/ANALISIS/OTRO SÍS, LA REC. DE CLI. Y LA SAT.  DE LOS CLI/SCRIPTS/ARBOL_ASPECTOS_SATISFACCION.ps", 
     title = "", pretty = TRUE,
     use.n = TRUE, horizontal = TRUE)

prp(fit1,type=4,extra=101,cex=.40,gap=0,space=0)

#IMPRESIÓN DE REGLAS
#rpart.rules(fit1)
printcp(fit1) # display the results 
predictions <- predict(fit1)
mse <- mean(abs(BD$SATISFACCION - predictions))
mse
